# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PythonCode\CAD\view\serial.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1207, 841)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.formGroupBox.setGeometry(QtCore.QRect(910, 10, 221, 201))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.open_serial_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_serial_button.setObjectName("open_serial_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.open_serial_button)
        self.close_serial_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_serial_button.setObjectName("close_serial_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.close_serial_button)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 20, 891, 191))
        self.groupBox.setObjectName("groupBox")
        self.tagTable = QtWidgets.QTableWidget(self.groupBox)
        self.tagTable.setGeometry(QtCore.QRect(10, 20, 562, 73))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagTable.sizePolicy().hasHeightForWidth())
        self.tagTable.setSizePolicy(sizePolicy)
        self.tagTable.setMinimumSize(QtCore.QSize(0, 71))
        self.tagTable.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tagTable.setFont(font)
        self.tagTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tagTable.setAutoScrollMargin(16)
        self.tagTable.setAlternatingRowColors(True)
        self.tagTable.setRowCount(0)
        self.tagTable.setColumnCount(8)
        self.tagTable.setObjectName("tagTable")
        self.tagTable.horizontalHeader().setDefaultSectionSize(70)
        self.tagTable.horizontalHeader().setMinimumSectionSize(70)
        self.tagTable.horizontalHeader().setStretchLastSection(False)
        self.tagTable.verticalHeader().setDefaultSectionSize(18)
        self.tagTable.verticalHeader().setMinimumSectionSize(18)
        self.anchorTable = QtWidgets.QTableWidget(self.groupBox)
        self.anchorTable.setGeometry(QtCore.QRect(590, 20, 291, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anchorTable.sizePolicy().hasHeightForWidth())
        self.anchorTable.setSizePolicy(sizePolicy)
        self.anchorTable.setMinimumSize(QtCore.QSize(0, 112))
        self.anchorTable.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.anchorTable.setFont(font)
        self.anchorTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.anchorTable.setAlternatingRowColors(True)
        self.anchorTable.setRowCount(5)
        self.anchorTable.setColumnCount(4)
        self.anchorTable.setObjectName("anchorTable")
        self.anchorTable.horizontalHeader().setDefaultSectionSize(70)
        self.anchorTable.horizontalHeader().setMinimumSectionSize(70)
        self.anchorTable.horizontalHeader().setStretchLastSection(False)
        self.anchorTable.verticalHeader().setVisible(False)
        self.anchorTable.verticalHeader().setDefaultSectionSize(18)
        self.anchorTable.verticalHeader().setHighlightSections(True)
        self.anchorTable.verticalHeader().setMinimumSectionSize(18)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(870, 230, 397, 556))
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 300))
        self.tabWidget.setObjectName("tabWidget")
        self.config_tab = QtWidgets.QWidget()
        self.config_tab.setObjectName("config_tab")
        self.showTagHistory = QtWidgets.QCheckBox(self.config_tab)
        self.showTagHistory.setGeometry(QtCore.QRect(20, 380, 109, 17))
        self.showTagHistory.setObjectName("showTagHistory")
        self.showGeoFencingMode = QtWidgets.QCheckBox(self.config_tab)
        self.showGeoFencingMode.setGeometry(QtCore.QRect(20, 50, 109, 17))
        self.showGeoFencingMode.setObjectName("showGeoFencingMode")
        self.zone1 = QtWidgets.QDoubleSpinBox(self.config_tab)
        self.zone1.setGeometry(QtCore.QRect(100, 90, 62, 22))
        self.zone1.setMaximum(300.0)
        self.zone1.setProperty("value", 2.0)
        self.zone1.setObjectName("zone1")
        self.zone2 = QtWidgets.QDoubleSpinBox(self.config_tab)
        self.zone2.setGeometry(QtCore.QRect(100, 130, 62, 22))
        self.zone2.setMaximum(300.0)
        self.zone2.setProperty("value", 4.0)
        self.zone2.setObjectName("zone2")
        self.label_z1 = QtWidgets.QLabel(self.config_tab)
        self.label_z1.setGeometry(QtCore.QRect(30, 90, 61, 20))
        self.label_z1.setObjectName("label_z1")
        self.label_z2 = QtWidgets.QLabel(self.config_tab)
        self.label_z2.setGeometry(QtCore.QRect(30, 130, 61, 20))
        self.label_z2.setObjectName("label_z2")
        self.inAlarm = QtWidgets.QRadioButton(self.config_tab)
        self.inAlarm.setGeometry(QtCore.QRect(130, 170, 91, 17))
        self.inAlarm.setChecked(True)
        self.inAlarm.setObjectName("inAlarm")
        self.outAlarm = QtWidgets.QRadioButton(self.config_tab)
        self.outAlarm.setGeometry(QtCore.QRect(20, 170, 91, 17))
        self.outAlarm.setObjectName("outAlarm")
        self.tagHistoryN = QtWidgets.QSpinBox(self.config_tab)
        self.tagHistoryN.setGeometry(QtCore.QRect(130, 380, 51, 22))
        self.tagHistoryN.setMinimum(1)
        self.tagHistoryN.setMaximum(128)
        self.tagHistoryN.setProperty("value", 20)
        self.tagHistoryN.setObjectName("tagHistoryN")
        self.showTagTable = QtWidgets.QCheckBox(self.config_tab)
        self.showTagTable.setGeometry(QtCore.QRect(20, 430, 109, 17))
        self.showTagTable.setChecked(True)
        self.showTagTable.setObjectName("showTagTable")
        self.showAnchorTable = QtWidgets.QCheckBox(self.config_tab)
        self.showAnchorTable.setGeometry(QtCore.QRect(20, 460, 109, 17))
        self.showAnchorTable.setChecked(True)
        self.showAnchorTable.setObjectName("showAnchorTable")
        self.showAnchorTagCorrectionTable = QtWidgets.QCheckBox(self.config_tab)
        self.showAnchorTagCorrectionTable.setEnabled(True)
        self.showAnchorTagCorrectionTable.setGeometry(QtCore.QRect(20, 490, 191, 17))
        self.showAnchorTagCorrectionTable.setChecked(False)
        self.showAnchorTagCorrectionTable.setObjectName("showAnchorTagCorrectionTable")
        self.showNavigationMode = QtWidgets.QCheckBox(self.config_tab)
        self.showNavigationMode.setGeometry(QtCore.QRect(20, 20, 151, 17))
        self.showNavigationMode.setChecked(True)
        self.showNavigationMode.setObjectName("showNavigationMode")
        self.filtering = QtWidgets.QComboBox(self.config_tab)
        self.filtering.setGeometry(QtCore.QRect(120, 260, 111, 22))
        self.filtering.setObjectName("filtering")
        self.label_z1_2 = QtWidgets.QLabel(self.config_tab)
        self.label_z1_2.setGeometry(QtCore.QRect(20, 260, 81, 20))
        self.label_z1_2.setObjectName("label_z1_2")
        self.useAutoPos = QtWidgets.QCheckBox(self.config_tab)
        self.useAutoPos.setEnabled(True)
        self.useAutoPos.setGeometry(QtCore.QRect(20, 210, 161, 17))
        self.useAutoPos.setChecked(False)
        self.useAutoPos.setObjectName("useAutoPos")
        self.label_logingstatus = QtWidgets.QLabel(self.config_tab)
        self.label_logingstatus.setGeometry(QtCore.QRect(20, 300, 91, 20))
        self.label_logingstatus.setObjectName("label_logingstatus")
        self.logging_pb = QtWidgets.QPushButton(self.config_tab)
        self.logging_pb.setGeometry(QtCore.QRect(120, 300, 111, 23))
        self.logging_pb.setObjectName("logging_pb")
        self.label_logingstatus_2 = QtWidgets.QLabel(self.config_tab)
        self.label_logingstatus_2.setGeometry(QtCore.QRect(20, 400, 51, 20))
        self.label_logingstatus_2.setText("")
        self.label_logingstatus_2.setObjectName("label_logingstatus_2")
        self.label_logfile = QtWidgets.QLabel(self.config_tab)
        self.label_logfile.setGeometry(QtCore.QRect(20, 330, 211, 20))
        self.label_logfile.setObjectName("label_logfile")
        self.label_logingstatus_3 = QtWidgets.QLabel(self.config_tab)
        self.label_logingstatus_3.setGeometry(QtCore.QRect(20, 240, 51, 20))
        self.label_logingstatus_3.setText("")
        self.label_logingstatus_3.setObjectName("label_logingstatus_3")
        self.tabWidget.addTab(self.config_tab, "")
        self.floorplan_tab = QtWidgets.QWidget()
        self.floorplan_tab.setObjectName("floorplan_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.floorplan_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 2, 1, 1)
        self.floorplanXScale_sb = QtWidgets.QDoubleSpinBox(self.floorplan_tab)
        self.floorplanXScale_sb.setMaximum(1000.0)
        self.floorplanXScale_sb.setObjectName("floorplanXScale_sb")
        self.gridLayout_2.addWidget(self.floorplanXScale_sb, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.floorplanXOff_sb = QtWidgets.QSpinBox(self.floorplan_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floorplanXOff_sb.sizePolicy().hasHeightForWidth())
        self.floorplanXOff_sb.setSizePolicy(sizePolicy)
        self.floorplanXOff_sb.setMinimum(-65536)
        self.floorplanXOff_sb.setMaximum(65535)
        self.floorplanXOff_sb.setObjectName("floorplanXOff_sb")
        self.gridLayout_2.addWidget(self.floorplanXOff_sb, 2, 1, 1, 1)
        self.floorplanPath_lb = QtWidgets.QLabel(self.floorplan_tab)
        self.floorplanPath_lb.setObjectName("floorplanPath_lb")
        self.gridLayout_2.addWidget(self.floorplanPath_lb, 0, 0, 1, 2)
        self.floorplanFlipY_cb = QtWidgets.QCheckBox(self.floorplan_tab)
        self.floorplanFlipY_cb.setText("")
        self.floorplanFlipY_cb.setObjectName("floorplanFlipY_cb")
        self.gridLayout_2.addWidget(self.floorplanFlipY_cb, 7, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 9, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 2, 1, 1)
        self.floorplanYScale_sb = QtWidgets.QDoubleSpinBox(self.floorplan_tab)
        self.floorplanYScale_sb.setMaximum(1000.0)
        self.floorplanYScale_sb.setObjectName("floorplanYScale_sb")
        self.gridLayout_2.addWidget(self.floorplanYScale_sb, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 2, 1, 1)
        self.floorplanYOff_sb = QtWidgets.QSpinBox(self.floorplan_tab)
        self.floorplanYOff_sb.setMinimum(-65536)
        self.floorplanYOff_sb.setMaximum(65536)
        self.floorplanYOff_sb.setObjectName("floorplanYOff_sb")
        self.gridLayout_2.addWidget(self.floorplanYOff_sb, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.floorplanFlipX_cb = QtWidgets.QCheckBox(self.floorplan_tab)
        self.floorplanFlipX_cb.setText("")
        self.floorplanFlipX_cb.setObjectName("floorplanFlipX_cb")
        self.gridLayout_2.addWidget(self.floorplanFlipX_cb, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.floorplan_tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.showOrigin = QtWidgets.QCheckBox(self.floorplan_tab)
        self.showOrigin.setObjectName("showOrigin")
        self.gridLayout.addWidget(self.showOrigin, 0, 0, 1, 1)
        self.scaleY_pb = QtWidgets.QPushButton(self.floorplan_tab)
        self.scaleY_pb.setObjectName("scaleY_pb")
        self.gridLayout.addWidget(self.scaleY_pb, 1, 2, 1, 1)
        self.scaleX_pb = QtWidgets.QPushButton(self.floorplan_tab)
        self.scaleX_pb.setObjectName("scaleX_pb")
        self.gridLayout.addWidget(self.scaleX_pb, 1, 0, 1, 1)
        self.origin_pb = QtWidgets.QPushButton(self.floorplan_tab)
        self.origin_pb.setObjectName("origin_pb")
        self.gridLayout.addWidget(self.origin_pb, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 8, 0, 1, 2)
        self.floorplanOpen_pb = QtWidgets.QPushButton(self.floorplan_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floorplanOpen_pb.sizePolicy().hasHeightForWidth())
        self.floorplanOpen_pb.setSizePolicy(sizePolicy)
        self.floorplanOpen_pb.setMinimumSize(QtCore.QSize(0, 0))
        self.floorplanOpen_pb.setObjectName("floorplanOpen_pb")
        self.gridLayout_2.addWidget(self.floorplanOpen_pb, 1, 0, 1, 1)
        self.saveFP = QtWidgets.QCheckBox(self.floorplan_tab)
        self.saveFP.setObjectName("saveFP")
        self.gridLayout_2.addWidget(self.saveFP, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.tabWidget.addTab(self.floorplan_tab, "")
        self.grid_tab = QtWidgets.QWidget()
        self.grid_tab.setObjectName("grid_tab")
        self.layoutWidget = QtWidgets.QWidget(self.grid_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 21, 178, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(45, 0))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridWidth_sb = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.gridWidth_sb.setDecimals(2)
        self.gridWidth_sb.setSingleStep(0.1)
        self.gridWidth_sb.setProperty("value", 0.5)
        self.gridWidth_sb.setObjectName("gridWidth_sb")
        self.gridLayout_3.addWidget(self.gridWidth_sb, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(45, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridHeight_sb = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.gridHeight_sb.setSingleStep(0.1)
        self.gridHeight_sb.setProperty("value", 0.5)
        self.gridHeight_sb.setObjectName("gridHeight_sb")
        self.gridLayout_3.addWidget(self.gridHeight_sb, 1, 1, 1, 1)
        self.gridShow = QtWidgets.QCheckBox(self.layoutWidget)
        self.gridShow.setObjectName("gridShow")
        self.gridLayout_3.addWidget(self.gridShow, 2, 0, 1, 1)
        self.tabWidget.addTab(self.grid_tab, "")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 220, 831, 541))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1207, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "俊杰UWB上位机"))
        self.formGroupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.s1__lb_1.setText(_translate("MainWindow", "串口检测："))
        self.s1__box_1.setText(_translate("MainWindow", "检测串口"))
        self.s1__lb_2.setText(_translate("MainWindow", "串口选择："))
        self.open_serial_button.setText(_translate("MainWindow", "打开串口"))
        self.close_serial_button.setText(_translate("MainWindow", "关闭串口"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.showTagHistory.setText(_translate("MainWindow", "Show Tag History"))
        self.showGeoFencingMode.setText(_translate("MainWindow", "Geo-Fencing Mode"))
        self.label_z1.setText(_translate("MainWindow", "Zone 1 (m)"))
        self.label_z2.setText(_translate("MainWindow", "Zone 2 (m)"))
        self.inAlarm.setText(_translate("MainWindow", "Alarm Inside"))
        self.outAlarm.setText(_translate("MainWindow", "Alarm Outside"))
        self.showTagTable.setText(_translate("MainWindow", "Show Tag Table"))
        self.showAnchorTable.setText(_translate("MainWindow", "Show Anchor Table"))
        self.showAnchorTagCorrectionTable.setText(_translate("MainWindow", "Show Anchor-Tag Correction Table"))
        self.showNavigationMode.setText(_translate("MainWindow", "Tracking/Navigation Mode"))
        self.label_z1_2.setText(_translate("MainWindow", "Filtering options:"))
        self.useAutoPos.setText(_translate("MainWindow", "Use Auto - Positioning"))
        self.label_logingstatus.setText(_translate("MainWindow", "Logging:"))
        self.logging_pb.setText(_translate("MainWindow", "Start"))
        self.label_logfile.setText(_translate("MainWindow", "Log filename"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_tab), _translate("MainWindow", "Configuration"))
        self.label_11.setText(_translate("MainWindow", "pixels"))
        self.label_9.setText(_translate("MainWindow", "pixesl/m"))
        self.label_3.setText(_translate("MainWindow", "X Offset"))
        self.floorplanPath_lb.setText(_translate("MainWindow", "No Floor Plan"))
        self.label_12.setText(_translate("MainWindow", "pixels"))
        self.label_10.setText(_translate("MainWindow", "pixels/m"))
        self.label_6.setText(_translate("MainWindow", "X Scale"))
        self.label_7.setText(_translate("MainWindow", "Flip X"))
        self.label_4.setText(_translate("MainWindow", "Y Offset"))
        self.label_5.setText(_translate("MainWindow", "Y Scale"))
        self.label_8.setText(_translate("MainWindow", "Flip Y"))
        self.showOrigin.setText(_translate("MainWindow", "Show Origin"))
        self.scaleY_pb.setText(_translate("MainWindow", "Y Scale"))
        self.scaleX_pb.setText(_translate("MainWindow", "X Scale"))
        self.origin_pb.setText(_translate("MainWindow", "Set Origin"))
        self.floorplanOpen_pb.setText(_translate("MainWindow", "Open"))
        self.saveFP.setText(_translate("MainWindow", "Save Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.floorplan_tab), _translate("MainWindow", "Floor Plan"))
        self.label.setText(_translate("MainWindow", "Width (m)"))
        self.label_2.setText(_translate("MainWindow", "Height (m)"))
        self.gridShow.setText(_translate("MainWindow", "Show Grid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.grid_tab), _translate("MainWindow", "Grid"))

